/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ListifyUI;

import User.DataArray;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    String Nama;
    String Password;
    public Login(String Nama, String Password) {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/project/Saly-26.png")));
        this.Nama = Nama;
        this.Password = Password;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        LogoLogin = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        minusButton = new javax.swing.JLabel();
        bgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(465, 391));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Register.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 340, 50, 30);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(90, 230, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Don’t have an account _.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 340, 160, 30);

        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Button Log In.png"))); // NOI18N
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });
        getContentPane().add(buttonLogin);
        buttonLogin.setBounds(180, 290, 130, 36);

        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Password.png"))); // NOI18N
        getContentPane().add(password);
        password.setBounds(90, 210, 80, 11);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(txtUsername);
        txtUsername.setBounds(90, 170, 250, 30);

        Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Username.png"))); // NOI18N
        getContentPane().add(Email);
        Email.setBounds(90, 150, 110, 11);

        LogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo login.png"))); // NOI18N
        getContentPane().add(LogoLogin);
        LogoLogin.setBounds(150, 40, 150, 83);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Close.png"))); // NOI18N
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(430, 0, 30, 30);

        minusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Minus.png"))); // NOI18N
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusButtonMouseClicked(evt);
            }
        });
        getContentPane().add(minusButton);
        minusButton.setBounds(400, 0, 30, 30);

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/LogIn.png"))); // NOI18N
        getContentPane().add(bgLogin);
        bgLogin.setBounds(0, 0, 470, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minusButtonMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        this.dispose(); // menutup Login
    }//GEN-LAST:event_closeButtonMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //Menuju ke Menu Registrasi
        Register Regist = new Register();
        Regist.setVisible(true);
        Regist.pack();
        Regist.setLocationRelativeTo(null);

        //menutup Login Form
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_formWindowOpened
    
    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked

        DataArray da = new DataArray(10);
        if (Nama.equals(txtUsername.getText()) && Password.equals(txtPassword.getText())){
            //Menuju ke Menu home
            Home home = new Home(txtUsername.getText(),txtPassword.getText());
            home.setVisible(true);
            home.pack();
            home.setLocationRelativeTo(null);
      
            
            //menutup login dan Main
            Main main = new Main();
            main.dispose();
            this.dispose();
        }
        else if (da.findUsername(txtUsername.getText()) && da.findPassword(txtPassword.getText())) {
            //Menuju ke Menu home
            Home home = new Home(txtUsername.getText(),txtPassword.getText());
            home.setVisible(true);
            home.pack();
            home.setLocationRelativeTo(null);
      
            
            //menutup login dan Main
            Main main = new Main();
            main.dispose();
            this.dispose();

        } else if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong !!");
            txtPassword.setText("");
            txtPassword.requestFocus();

        } else if (!da.findPassword(txtPassword.getText())) {
            System.out.println(da.findPassword(txtPassword.getText()));
            JOptionPane.showMessageDialog(null, "Password Salah !!");

            txtPassword.setText("");
            txtPassword.requestFocus();

        } else {
            JOptionPane.showMessageDialog(null, "Username atau Password Salah !!");
            txtUsername.setText("");
            txtPassword.setText("");
            txtUsername.requestFocus();
        }

    }//GEN-LAST:event_buttonLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel LogoLogin;
    private javax.swing.JLabel bgLogin;
    private javax.swing.JLabel buttonLogin;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel minusButton;
    private javax.swing.JLabel password;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
