package ListifyUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import User.DataArray;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/project/Saly-26.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        LabelPassword = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        LabelOccupation = new javax.swing.JLabel();
        Occupation = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        logoSignin = new javax.swing.JLabel();
        minusButton = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        bgRegister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(557, 529));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Log In.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 480, 60, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Already have an account _.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 480, 180, 13);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Button Register.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 420, 120, 40);
        getContentPane().add(Passwordtxt);
        Passwordtxt.setBounds(130, 360, 280, 30);

        LabelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Password.png"))); // NOI18N
        getContentPane().add(LabelPassword);
        LabelPassword.setBounds(130, 330, 130, 20);

        LabelEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/E-mail.png"))); // NOI18N
        getContentPane().add(LabelEmail);
        LabelEmail.setBounds(130, 270, 110, 20);

        LabelOccupation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Occupation.png"))); // NOI18N
        getContentPane().add(LabelOccupation);
        LabelOccupation.setBounds(130, 210, 130, 20);

        Occupation.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Occupation.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(Occupation);
        Occupation.setBounds(130, 230, 280, 30);

        Name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Name.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(Name);
        Name.setBounds(130, 170, 280, 30);

        Email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(Email);
        Email.setBounds(130, 290, 280, 30);

        labelNama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Name.png"))); // NOI18N
        getContentPane().add(labelNama);
        labelNama.setBounds(130, 150, 110, 20);

        logoSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Logo Sign Up.png"))); // NOI18N
        getContentPane().add(logoSignin);
        logoSignin.setBounds(190, 20, 160, 140);

        minusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Minus.png"))); // NOI18N
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusButtonMouseClicked(evt);
            }
        });
        getContentPane().add(minusButton);
        minusButton.setBounds(490, 0, 28, 40);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Close.png"))); // NOI18N
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(520, 0, 30, 40);

        bgRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Register-bg.png"))); // NOI18N
        getContentPane().add(bgRegister);
        bgRegister.setBounds(0, 0, 560, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minusButtonMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        this.dispose(); // menutup Register 
    }//GEN-LAST:event_closeButtonMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        DataArray da = new DataArray(10);

        if (Name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " tidak boleh kosong !!");
            Name.setText("");
            Name.requestFocus();
        } else if (!da.findUsername(Name.getText())) {
            JOptionPane.showMessageDialog(null, "Registrasi berhasil");
            da.Regist(Name.getText(), Occupation.getText(), Email.getText(), Passwordtxt.getText());
            da.insert(Name.getText(), Passwordtxt.getText());

//Menuju ke Menu Registrasi
            Login Regist = new Login(Name.getText(), Passwordtxt.getText());
            Regist.setVisible(true);
            Regist.pack();
            Regist.setLocationRelativeTo(null);

            //menutup Regist Form
            Register n = new Register();
            n.dispose();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Maaf, username tidak tersedia");
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    public String gettName() {
        String Nama = Name.getText();
        System.out.println(Nama);
        return Nama;
    }
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //Menuju ke Menu Registrasi
        Login in = new Login(Name.getText(), Passwordtxt.getText());
        in.setVisible(true);
        in.pack();
        in.setLocationRelativeTo(null);

        //menutup Login Form
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelOccupation;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Occupation;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JLabel bgRegister;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel logoSignin;
    private javax.swing.JLabel minusButton;
    // End of variables declaration//GEN-END:variables

}
